# First Assesment notebook

In [1]:
import pandas as pd

In [2]:
# Read the dataset into a pandas dataframe

data = pd.read_excel('Data1.xlsx')

In [3]:
# View the first five rows of the dataset

data.head(5)

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton          5377489   
1  rockport total plant                coal       ton         10486945   
2                gorgas                coal       ton          2978683   
3                 barry                coal       ton          3739484   
4             chickasaw                 gas       mcf            40533   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

In [4]:
# Get a description of the dataset

data.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [5]:
# Qestion 1

A = [1,2,3,4,5,6]
B = [13, 21, 34]

In [6]:
print(A)

[1, 2, 3, 4, 5, 6]


In [7]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]


In [8]:
A.append(B)

In [9]:
print(A)

[1, 2, 3, 4, 5, 6, [13, 21, 34]]


In [10]:
# Question 2

import numpy as np

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.array([[1,0,0],[0,1,0],[0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
data.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [14]:
# Question 3

data[data['fuel_cost_per_unit_burned']==-276.080000].index.values

array([7733], dtype=int64)

In [15]:
data[7733:].head(1)

record_id  utility_id_ferc1  report_year  \
7733  f1_fuel_2000_12_194_3_3               194         2000   

         plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
7733  nelson dewey unit 2               waste       ton               39   

      fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
7733               0.0155                    -276.08   

      fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
7733                       -174.67               -8.906

In [16]:
# Question 4


# from data.describe() which was obtained earlier, we found the std and 75th percentile to be:
    
#    8.49 and 17.01

In [17]:
# Question 5

data['fuel_qty_burned'].skew()

15.851495469109503

In [18]:
# Question 5

data['fuel_qty_burned'].skew()

15.851495469109503

In [19]:
data['fuel_qty_burned'].kurtosis()

651.3694501337732

In [20]:
# Question 5

data['fuel_qty_burned'].skew()

15.851495469109503

In [21]:
# Question 5

data['fuel_qty_burned'].skew()

15.851495469109503

In [22]:
#Question 6


data.isnull().sum()   # It appears that fuel_unit has the most missing values.

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [23]:
# count of categorical values (including missing category)

c =data['fuel_unit'].isnull().value_counts(normalize = True)

c

False    0.993903
True     0.006097
Name: fuel_unit, dtype: float64

In [24]:
# Make a percentage of each value

c*=100

c

False    99.390306
True      0.609694
Name: fuel_unit, dtype: float64

In [25]:
# Question 7

data['fuel_unit']   # The values are categorical

0        ton
1        ton
2        ton
3        ton
4        mcf
        ... 
29518    mcf
29519    mcf
29520    mcf
29521    ton
29522    mcf
Name: fuel_unit, Length: 29523, dtype: object

In [26]:
# Question 8
# Making a correlation table

data.corr()

utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                      1.000000     0.093323        -0.057447   
report_year                           0.093323     1.000000         0.012952   
fuel_qty_burned                      -0.057447     0.012952         1.000000   
fuel_mmbtu_per_unit                  -0.066946    -0.110853        -0.080946   
fuel_cost_per_unit_burned            -0.037863     0.013599        -0.018535   
fuel_cost_per_unit_delivered         -0.016414    -0.014043        -0.003551   
fuel_cost_per_mmbtu                   0.006122     0.010261        -0.001896   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                        -0.066946                  -0.037863   
report_year                             -0.110853                   0.013599   
fuel_qty_burned                         -0.080946                  -0.018535   
fuel_mmbtu_per_unit                      1.000000                  -0.010034   
fuel_cost_per_unit_burned               -0.010034                   1.000000   
fuel_cost_per_unit_delivered            -0.009039                   0.011007   
fuel_cost_per_mmbtu                     -0.005884                  -0.000437   

                              fuel_cost_per_unit_delivered  \
utility_id_ferc1                                 -0.016414   
report_year                                      -0.014043   
fuel_qty_burned                                  -0.003551   
fuel_mmbtu_per_unit                              -0.009039   
fuel_cost_per_unit_burned                         0.011007   
fuel_cost_per_unit_delivered                      1.000000   
fuel_cost_per_mmbtu                              -0.000109   

                              fuel_cost_per_mmbtu  
utility_id_ferc1                         0.006122  
report_year                              0.010261  
fuel_qty_burned                         -0.001896  
fuel_mmbtu_per_unit                     -0.005884  
fuel_cost_per_unit_burned               -0.000437  
fuel_cost_per_unit_delivered            -0.000109  
fuel_cost_per_mmbtu                      1.000000

In [27]:
# Question 10

data[data['fuel_cost_per_unit_delivered']==7.964521e+06].index.values

array([3564], dtype=int64)

In [28]:
data[3564:].head(1)

# The Year was 1997

record_id  utility_id_ferc1  report_year plant_name_ferc1  \
3564  f1_fuel_1997_12_9_0_8                 9         1997     peach bt 2&3   

     fuel_type_code_pudl fuel_unit  fuel_qty_burned  fuel_mmbtu_per_unit  \
3564             nuclear    gramsU           210474             0.000065   

      fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
3564                     37.847                     7964521.0   

      fuel_cost_per_mmbtu  
3564                0.578